Traceback (most recent call last):
  File "/home/phuc/Practice/DataScience/DSProject/venv/lib/python3.10/site-packages/lockfile/pidlockfile.py", line 77, in acquire
    write_pid_to_pidfile(self.path)
  File "/home/phuc/Practice/DataScience/DSProject/venv/lib/python3.10/site-packages/lockfile/pidlockfile.py", line 161, in write_pid_to_pidfile
    pidfile_fd = os.open(pidfile_path, open_flags, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: 'job_airflow/airflow-webserver-monitor.pid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phuc/Practice/DataScience/DSProject/venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/phuc/Practice/DataScience/DSProject/venv/lib/python3.10/site-packages/airflow/__main__.py", line 57, in main
    args.func(args)
  File "/home/phuc/Practice/DataScience/DSProject/venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/phuc/Practice/DataScience/DSProject/venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/home/phuc/Practice/DataScience/DSProject/venv/lib/python3.10/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/phuc/Practice/DataScience/DSProject/venv/lib/python3.10/site-packages/airflow/cli/commands/webserver_command.py", line 492, in webserver
    with ctx:
  File "/home/phuc/Practice/DataScience/DSProject/venv/lib/python3.10/site-packages/daemon/daemon.py", line 365, in __enter__
    self.open()
  File "/home/phuc/Practice/DataScience/DSProject/venv/lib/python3.10/site-packages/daemon/daemon.py", line 357, in open
    self.pidfile.__enter__()
  File "/home/phuc/Practice/DataScience/DSProject/venv/lib/python3.10/site-packages/lockfile/__init__.py", line 197, in __enter__
    self.acquire()
  File "/home/phuc/Practice/DataScience/DSProject/venv/lib/python3.10/site-packages/daemon/pidfile.py", line 49, in acquire
    super().acquire(timeout, *args, **kwargs)
  File "/home/phuc/Practice/DataScience/DSProject/venv/lib/python3.10/site-packages/lockfile/pidlockfile.py", line 91, in acquire
    raise LockFailed("failed to create %s" % self.path)
lockfile.LockFailed: failed to create job_airflow/airflow-webserver-monitor.pid
