[2023-12-03T09:21:45.030+0700] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.save_data manual__2023-12-03T02:16:23.978630+00:00 [queued]>
[2023-12-03T09:21:45.037+0700] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.save_data manual__2023-12-03T02:16:23.978630+00:00 [queued]>
[2023-12-03T09:21:45.037+0700] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2023-12-03T09:21:45.047+0700] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): save_data> on 2023-12-03 02:16:23.978630+00:00
[2023-12-03T09:21:45.050+0700] {standard_task_runner.py:57} INFO - Started process 70125 to run task
[2023-12-03T09:21:45.053+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'save_data', 'manual__2023-12-03T02:16:23.978630+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmprc97rf4t']
[2023-12-03T09:21:45.053+0700] {standard_task_runner.py:85} INFO - Job 9: Subtask save_data
[2023-12-03T09:21:45.079+0700] {task_command.py:416} INFO - Running <TaskInstance: my_first_dag.save_data manual__2023-12-03T02:16:23.978630+00:00 [running]> on host phuc-ASUS
[2023-12-03T09:21:45.116+0700] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='save_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T02:16:23.978630+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-03T02:16:23.978630+00:00'
[2023-12-03T09:21:45.116+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-03T09:21:45.117+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/phuc/Practice/DataScience/DSProject/job_transformation && python3 test_spark.py write-to-delta-table']
[2023-12-03T09:21:45.122+0700] {subprocess.py:86} INFO - Output:
[2023-12-03T09:21:45.328+0700] {subprocess.py:93} INFO - Usage: test_spark.py [OPTIONS]
[2023-12-03T09:21:45.329+0700] {subprocess.py:93} INFO - Try 'test_spark.py --help' for help.
[2023-12-03T09:21:45.329+0700] {subprocess.py:93} INFO - ╭─ Error ──────────────────────────────────────────────────────────────────────╮
[2023-12-03T09:21:45.329+0700] {subprocess.py:93} INFO - │ Got unexpected extra argument (write-to-delta-table)                         │
[2023-12-03T09:21:45.330+0700] {subprocess.py:93} INFO - ╰──────────────────────────────────────────────────────────────────────────────╯
[2023-12-03T09:21:45.364+0700] {subprocess.py:97} INFO - Command exited with return code 2
[2023-12-03T09:21:45.371+0700] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/phuc/Practice/DataScience/DSProject/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-12-03T09:21:45.373+0700] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=my_first_dag, task_id=save_data, execution_date=20231203T021623, start_date=20231203T022145, end_date=20231203T022145
[2023-12-03T09:21:45.387+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task save_data (Bash command failed. The command returned a non-zero exit code 2.; 70125)
[2023-12-03T09:21:45.425+0700] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-03T09:21:45.435+0700] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
