[2023-12-02T14:06:05.264+0700] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.crawl_data manual__2023-12-02T07:06:03.176940+00:00 [queued]>
[2023-12-02T14:06:05.268+0700] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.crawl_data manual__2023-12-02T07:06:03.176940+00:00 [queued]>
[2023-12-02T14:06:05.268+0700] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-12-02T14:06:05.275+0700] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): crawl_data> on 2023-12-02 07:06:03.176940+00:00
[2023-12-02T14:06:05.277+0700] {standard_task_runner.py:57} INFO - Started process 94063 to run task
[2023-12-02T14:06:05.278+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'crawl_data', 'manual__2023-12-02T07:06:03.176940+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp6oej0lox']
[2023-12-02T14:06:05.279+0700] {standard_task_runner.py:85} INFO - Job 12: Subtask crawl_data
[2023-12-02T14:06:05.296+0700] {task_command.py:416} INFO - Running <TaskInstance: my_first_dag.crawl_data manual__2023-12-02T07:06:03.176940+00:00 [running]> on host phuc-ASUS
[2023-12-02T14:06:05.327+0700] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MY_NAME' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='crawl_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-02T07:06:03.176940+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-02T07:06:03.176940+00:00'
[2023-12-02T14:06:05.327+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-02T14:06:05.328+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'scrapy crawl quotes']
[2023-12-02T14:06:05.333+0700] {subprocess.py:86} INFO - Output:
[2023-12-02T14:06:05.584+0700] {subprocess.py:93} INFO - Scrapy 2.11.0 - no active project
[2023-12-02T14:06:05.585+0700] {subprocess.py:93} INFO - 
[2023-12-02T14:06:05.585+0700] {subprocess.py:93} INFO - Unknown command: crawl
[2023-12-02T14:06:05.585+0700] {subprocess.py:93} INFO - 
[2023-12-02T14:06:05.585+0700] {subprocess.py:93} INFO - Use "scrapy" to see available commands
[2023-12-02T14:06:05.647+0700] {subprocess.py:97} INFO - Command exited with return code 2
[2023-12-02T14:06:05.651+0700] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/phuc/Practice/DataScience/DSProject/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-12-02T14:06:05.653+0700] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=my_first_dag, task_id=crawl_data, execution_date=20231202T070603, start_date=20231202T070605, end_date=20231202T070605
[2023-12-02T14:06:05.665+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task crawl_data (Bash command failed. The command returned a non-zero exit code 2.; 94063)
[2023-12-02T14:06:05.691+0700] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-02T14:06:05.710+0700] {dagrun.py:743} ERROR - Failed to get task for ti <TaskInstance: my_first_dag.multiply_my_number_by_23 manual__2023-12-02T07:06:03.176940+00:00 [None]>. Marking it as removed.
[2023-12-02T14:06:05.715+0700] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
